title: "ARTISAN â€” Georgia Tech"
description: "Center for Artificial Intelligence in Science & Engineering at Georgia Tech"
# If a theme is specified, comment it out to fully control the look:
# theme: minima
# Or be explicit:
theme: null
markdown: kramdown
