title: "ARTISAN â€” Georgia Tech"
description: "Center for Artificial Intelligence in Science and Engineering at Georgia Tech"
baseurl: ""
url: "https://gt-artisan.github.io"
theme: null
markdown: kramdown

nav:
  - { label: "Home", href: "/" }
  - { label: "Research", href: "/research" }
  - { label: "Projects", href: "/projects" }
  - { label: "Scientific Software", href: "/scientific-software" }
  - { label: "Events", href: "/events" }
  - { label: "ARTISAN Team", href: "/team" }
  - { label: "Contact", href: "/contact" }
  - { label: "Careers", href: "/careers" }